use_frameworks!

platform :ios, '8.0'

target 'MGZPersonInfoCategoryKit_Example' do
  pod "CTMediator"
  pod 'MGZPersonInfoCategoryKit', :path => '../'

  target 'MGZPersonInfoCategoryKit_Tests' do
    inherit! :search_paths

    
  end
end
